//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisticSPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
    }
}
